apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas:
    '[object Object]': null
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: my-secret
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: my-secret
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: myapp
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
