apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: myapp
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
